name: Node.js CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        node-version: [12.x, 13.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing required packages
      run: npm install --no-fund
    - name: Installing pkg
      run: npm install pkg -g
    - name: Running test build
      run: pkg /home/runner/work/diep.io-clone/diep.io-clone -d
      env:
        CI: true
